# Generated by Django 5.0.1 on 2026-02-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_base64",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True,
                default="Software Engineer and ambitious learner exploring modern web development and algorithms. Focused on daily consistency.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, default="Earth", max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.CharField(
                blank=True,
                default="React,Django,Python,UI/UX,Algorithms",
                max_length=300,
            ),
        ),
    ]
